/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    Greeting: typeof import('./src/components/Greeting.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IMdiBloodCircle: typeof import('~icons/mdi/blood-circle')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/swiper.vue')['default']
  }
}
